### ISSUE TITLE
Bot not registering commands properly

### ISSUE THREAD

**Issue by CookieKenneth** [CookieKenneth/bananabot#8]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 857, in on_message
    yield from self.process_commands(message)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 345, in prepare
    yield from self._parse_arguments(ctx)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 304, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "C:\Users\kenne\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 212, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.').format(param)
AttributeError: 'MissingRequiredArgument' object has no attribute 'format'
```

**Comment by LordCage** [comment]
raise MissingRequiredArgument('{0.name} is a required argument that is missing.').format(param)
AttributeError: 'MissingRequiredArgument' object has no attribute 'format'

^^ your trying to execute something however your missing the required arguments.
Check the current code you have.
